# Generated by Django 4.2 on 2023-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_simulator',
            field=models.BooleanField(blank=True, help_text='Whether the device is a simulator/emulator', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_rooted_device',
            field=models.BooleanField(blank=True, help_text='Whether the device is rooted/jailbroken', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_vpn_enabled',
            field=models.BooleanField(blank=True, help_text='Whether a VPN is active on the device', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the device location', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the device location', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, help_text='City based on IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, help_text='Country based on IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='continent',
            field=models.CharField(blank=True, help_text='Continent based on IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_simulator',
            field=models.BooleanField(blank=True, help_text='Whether the device is a simulator/emulator', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_rooted_device',
            field=models.BooleanField(blank=True, help_text='Whether the device is rooted/jailbroken', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_vpn_enabled',
            field=models.BooleanField(blank=True, help_text='Whether a VPN is active on the device', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the device location', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the device location', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='city',
            field=models.CharField(blank=True, help_text='City based on IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='country',
            field=models.CharField(blank=True, help_text='Country based on IP geolocation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='continent',
            field=models.CharField(blank=True, help_text='Continent based on IP geolocation', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['country'], name='analytics_ev_country_dfdab9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city'], name='analytics_ev_city_a3ca96_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['country'], name='analytics_se_country_b02525_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['city'], name='analytics_se_city_7c1dd4_idx'),
        ),
    ] 