# Generated by Django 5.2.1 on 2025-05-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_migrate_existing_data_to_normalized_structure"),
    ]

    operations = [
        # Remove temporary fields from Event model
        migrations.RemoveField(
            model_name='event',
            name='temp_device_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_app_version',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_os_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_os_version',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_ip_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_is_simulator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_is_rooted_device',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_is_vpn_enabled',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='temp_continent',
        ),
        
        # Remove temporary fields from Session model
        migrations.RemoveField(
            model_name='session',
            name='temp_device_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_app_version',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_os_name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_os_version',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_ip_address',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_is_simulator',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_is_rooted_device',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_is_vpn_enabled',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_city',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_country',
        ),
        migrations.RemoveField(
            model_name='session',
            name='temp_continent',
        ),
    ]
